### ISSUE TITLE
 There is no answers for this form 😔

### ISSUE THREAD

**Issue by craziks-creator** [jagadish-ravichandran/Form_Telegram_Bot#1]
After answering successfully by users, bot is showing `There is no answers for this form 😔`
to me. Why???

**Comment by craziks-creator** [comment]
It's not showing answers plz..

**Comment by jagadish-ravichandran** [comment]
Fixing the issue.

**Comment by craziks-creator** [comment]
> Fixing the issue.

Bro Have you fixed the issue? 🙏

**Comment by craziks-creator** [comment]
??

**Comment by craziks-creator** [comment]
Previous Error solved. But For Groups in anonymous mode it's still showing `There is no answers for this form 😔`

**Comment by jagadish-ravichandran** [comment]
For now, the feature is not supported. I'm working on it. Thanks for the interests.

**Comment by jagadish-ravichandran** [comment]
Solved anonymous user form creation
